spring:
  application:
    name: spring-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port:
        dashboard: localhost:8080
    gateway:
      #设置与服务注册与发现相结合，这样便可采用服务名的路由策略
      discovery:
        locator:
          enabled: true
      #配置路由规则
      routes:
        #自定义路由id  after_route 路由之后 before_route 路由之前 between_router 路由中...详官网：spring.io
        - id: consumer
          #lb->loadBalanceClinet 方式请求 后面接注册到nacos的服务名
          uri: lb://nacos-consumer-feign
          predicates:
            # Method 方法谓词，此处为 get、post请求
            - Method=GET,POST
server:
  port: 8000
feign:
  sentinel:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org.springframework.cloud.gateway: debug
